name: 'Super Labeler'
description: 'A superpowered issue and pull request labeler for Github Actions.'
author: 'IvanFon'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
    required: true
  config:
    description: 'Config file path'
    default: '.github/labels.json'
    required: false
  showLogs:
    description: Show logs with info like total number of issues found, stale issues, closed etc.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'tag'
